<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,2,1,'5pyA5paw5L2c5ZOB');
$cfg_Cs[2]=array(1,2,1,'5bmz6Z2i6K6+6K6h');
$cfg_Cs[3]=array(1,2,1,'5pGE5b2x6Im65pyv');
$cfg_Cs[4]=array(1,2,1,'QVBQ5byA5Y+R');
$cfg_Cs[5]=array(0,1,1,'5paw6Ze7');
$cfg_Cs[6]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[7]=array(0,1,1,'6IGU57O7');
$cfg_Cs[8]=array(0,14,1,'5bm754Gv54mH');
$cfg_Cs[9]=array(0,1,1,'5a6i5oi3');
?>