<div class="ms-grid-item col-lg-6 col-md-12">
          <article class="ms-post-item post type-post status-publish format-standard has-post-thumbnail hentry category-history category-inspiration tag-observation tag-urban tag-walk"> <a href="[field:arcurl/]" data-type="page-transition">
            <div class="post-item__img"> <img width="569" height="380" src="[field:picname/]" /> </div>
            </a>
            <div class="post-item__info"> <a href="[field:arcurl/]" data-type="page-transition">
              <h5 class="post-item__title h5">[field:title/]</h5>
              </a>
              <div class="post-item__bottom"> <a href="[field:arcurl/]" data-type="page-transition">
                <div class="post-item__date"> [field:pubdate function="MyDate('Y-m-d',@me)"/] </div>
                <div class="post-item__link"> read more </div>
                </a> </div>
            </div>
          </article>
        </div>