<div class="swiper-slide" data-swiper-autoplay="5000">
          <div class="slide-inner" data-swiper-parallax="45%">
            <div class="overlay"></div>
            <div class="slide-inner--image" style="background-image: url('[field:picname/]');"></div>
            <div class="slide-inner--info">
              <h1 class="h1" data-swiper-parallax="-400px">[field:title/]</h1>
              <h3 style="color: #fff;line-height: 1.6em;font-size: 24px;font-weight: 200;">[field:description/]</h3>
              <a href="[field:redirecturl/]" data-type="page-transition" class="ms-btn--slider">[field:shorttitle/]</a> </div>
          </div>
        </div>