<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/180914/1-1P914150P3.jpg ",93,259);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/180914/1-1P914150P3.jpg";
$z[1][4]['text']="百度云测试图集";
$z[1][4]['width']="1920";
$z[1][4]['height']="1200";
$z[2]=Array("img"," /uploads/allimg/180914/1-1P914150P3-50.jpg ",261,412);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/180914/1-1P914150P3-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1920";
$z[2][4]['height']="1275";
$z[3]=Array("img"," /uploads/allimg/180914/1-1P914150P3-51.jpg ",414,565);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/180914/1-1P914150P3-51.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1732";
$z[3][4]['height']="1155";

?>