<div class="album-item ms-grid-item col-lg-4 col-md-6 albums type-albums status-publish hentry albums_categories-creative"> <a href="[field:arcurl/]" data-type="page-transition">
          <div class="album-item__overlay"> <span class="album-item__cover"></span>
            <h5 class="h5">[field:title/]</h5>
          </div>
          <div class="album-item__img" style="background-image: url([field:picname/])"></div>
          </a> </div>