<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/180914/1-1P914153535.jpg ",93,239);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/180914/1-1P914153535.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1920";
$z[1][4]['height']="959";
$z[2]=Array("img"," /uploads/allimg/180914/1-1P914153536.jpg ",241,388);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/180914/1-1P914153536.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1910";
$z[2][4]['height']="1200";
$z[3]=Array("img"," /uploads/allimg/180914/1-1P914153536-50.jpg ",390,543);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/180914/1-1P914153536-50.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1400";
$z[3][4]['height']="1033";
$z[4]=Array("img"," /uploads/allimg/180914/1-1P914153536-51.jpg ",545,697);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/180914/1-1P914153536-51.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1140";
$z[4][4]['height']="757";

?>