<?php
$z[0]=Array("global","",358,384);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",466,492);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channel","\r\n          <li id=\"menu-item-165\" class=\"menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item ms-nav-item\"><a href=\"[field:typelink/]\" data-type=\"page-transition\"><span class=\"nav-item__btn\">[field:typename/]</span></a></li>\r\n          ",1096,1414);
$z[2][4]=array();
$z[2][4]['type']="top";

?>