<?php
$z[0]=Array("global","",328,355);
$z[0][4]=array();
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",393,423);
$z[1][4]=array();
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",496,522);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",3761,3796);
$z[3][4]=array();
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n        <div class=\"swiper-slide\" data-swiper-autoplay=\"5000\">\r\n          <div class=\"slide-inner\" data-swiper-parallax=\"45%\">\r\n            <div class=\"overlay\"></div>\r\n            <div class=\"slide-inner--image\" style=\"background-image: url('[field:picname/]');\"></div>\r\n            <div class=\"slide-inner--info\">\r\n              <h1 class=\"h1\" data-swiper-parallax=\"-400px\">[field:title/]</h1>\r\n              <h3 style=\"color: #fff;line-height: 1.6em;font-size: 24px;font-weight: 200;\">[field:ms/]</h3>\r\n              <a href=\"[field:lj/]\" data-type=\"page-transition\" class=\"ms-btn--slider\">Take a Look</a> </div>\r\n          </div>\r\n        </div>\r\n        ",4023,4768);
$z[4][4]=array();
$z[4][4]['typeid']="8";
$z[4][4]['row']="6";
$z[4][4]['addfields']="lj,ms";
$z[4][4]['channelid']="14";
$z[5]=Array("type","<span>[field:ID function='GetTotalArc(@me)'/]</span>",5230,5316);
$z[5][4]=array();
$z[5][4]['typeid']="8";

?>